=== adrianeboyd/Synpathy/src/ims/tiger/resources/export/TIGERExportRegistry.dtd
<!ELEMENT registry (stylesheet+)>
<!ATTLIST registry  version  CDATA  #REQUIRED>

<!ELEMENT stylesheet EMPTY>
<!ATTLIST stylesheet id             ID  #REQUIRED>
<!ATTLIST stylesheet name           CDATA  #REQUIRED>
<!ATTLIST stylesheet sentence_xslt  CDATA  #REQUIRED>

=== adrianeboyd/Synpathy/src/ims/tiger/resources/export/TIGERExportRegistry.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE registry SYSTEM "TIGERExportRegistry.dtd">


<registry version="1.0">

  <stylesheet id="graph_alltokens"
              name="sentence format (all tokens)"
              sentence_xslt="graph_alltokens.xsl" />

  <stylesheet id="graph_tokensmatched"
              name="sentence format (all matching tokens)"
              sentence_xslt="graph_tokensmatched.xsl" />

  <stylesheet id="graph_tokensmarked"
              name="sentence format (all tokens, matching tokens marked)"
              sentence_xslt="graph_tokensmarked.xsl" />

  <stylesheet id="graph_tokensandpos"
              name="sentence format (all tokens incl. part-of-speech)"
              sentence_xslt="graph_tokensandpos.xsl" />

  <stylesheet id="variables_tokens"
              name="variables and their tokens"
              sentence_xslt="variables_tokens.xsl" />

  <stylesheet id="variables_values"
              name="variables and their values"
              sentence_xslt="variables_values.xsl" />

  <stylesheet id="bracketing"
              name="bracketing format"
              sentence_xslt="bracketing.xsl" />

  <stylesheet id="cfrules"
              name="context-free rules"
              sentence_xslt="cfrules.xsl" />

  <stylesheet id="sentence_numbers"
              name="list of sentence numbers (to be processed by Annotate)"
              sentence_xslt="annotate.xsl" />

</registry>
